### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by naoufalzerai**
fix duplicate files

### CODE REVIEW

**Review by cassidoo — APPROVED** [review]
Thank you for fixing this!

**Comment by benjifriedman** [comment]
I'm still seeing a doubled posts list, even with a fresh install 😢

**Comment by cassidoo** [comment]
> I'm still seeing a doubled posts list, even with a fresh install 😢

Hmm okay, I'll reopen #27 and check it out, sorry about that.

**Comment by benjifriedman** [comment]
That fixed it, thank you 🙏

**Pull request merged**
